package com.itemlog.model;

public enum EventType {
    PICKUP, DROP,
    INVENTORY_ADD, INVENTORY_REMOVE,
    CONTAINER_INSERT, CONTAINER_REMOVE,
    DEATH_DROP, DEATH_KEEP,
    CRAFT_INPUT, CRAFT_RESULT,
    SMELT_INPUT, SMELT_RESULT,
    CONSUME, DESTROY, OTHER
}